### PR TITLE
Bump to version 0.2

### PR DESCRIPTION
**Pull request by ahmader**
- Replaced GlobalSettings with SiteSettings (Plugin configuration is now from admin > settings > login).
- Internationalization ready.
- Using the oAuth2UserInfo database with providers.
- Dealing with existing accounts.
- Added Icon to login button.
- Fixed README.

### CODE REVIEW

**Comment by SamSaffron** [comment]
This has fallen between cracks, @davidtaylorhq does this look good to merge, seems fine to me.

**Comment by davidtaylorhq** [comment]
Unfortunately I think we've left this a little too long to merge cleanly. It looks like this PR was written before all the new Authentication changes, so it's using the 'old method' of storing associations in the database. 

There are a few other out-of-date things, such as using SCSS variables for the fontawesome icon. And also, the migration from GlobalSettings to SiteSettings will break the plugin for any existing users.

A few people have reported success using the [OpenID connect plugin](https://meta.discourse.org/t/openid-connect-authentication-plugin/103632?u=david) for Azure AD integration, so my preference would be to deprecate this plugin in favour of that. What do you think @SamSaffron?

**Comment by ahmader** [comment]
@davidtaylorhq I can update the out-of-date packages and review it again.

**Comment by davidtaylorhq** [comment]
@ahmader if you'd like to, that would be great. However, I'd strongly recommend that you try out the OpenID-connect plugin, and see if that works for you. It's used by a lot of people, and is being actively maintained/developed.

If you want to continue working on this one, the main change would be to migrate it to our new "manager authenticator" system: https://meta.discourse.org/t/adding-a-new-managed-authentication-method-to-discourse/106695

**Comment by SamSaffron** [comment]
@ahmader  I am closing this off for now, feel free to open another PR with the new managed auth system support!

**Pull request closed without merging**
